name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    container: swift:5.9
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v

  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
